---
- name: Compute
  count: 1
  defaults:
    profile: compute
    networks:
    - network: external
      subnet: external_subnet
    - network: internal_api
      subnet: internal_api_subnet
    - network: storage
      subnet: storage_subnet
    - network: storage_mgmt
      subnet: storage_mgmt_subnet
    - network: tenant
      subnet: tenant_subnet
    config_drive:
      cloud_config:
        network:
          config: disabled
    network_config:
      template: /home/centos/dual-nic-multi-vlan.yaml.j2
      default_route_network:
      - external
- name: Controller
  count: 1
  defaults:
    profile: control
    networks:
    - network: external
      subnet: external_subnet
    - network: internal_api
      subnet: internal_api_subnet
    - network: storage
      subnet: storage_subnet
    - network: storage_mgmt
      subnet: storage_mgmt_subnet
    - network: tenant
      subnet: tenant_subnet
    config_drive:
      cloud_config:
        network:
          config: disabled
    network_config:
      template: /home/centos/dual-nic-multi-vlan.yaml.j2
      default_route_network:
      - external
